version: 3.8.5

services:
  db:
    hostname: db
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  bot:
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
    env_file:
      - .env

volumes:
  db-data:
  redis-data: